-- SQL statements generated by parsing the csv file: cover.csv
-- using field: sourceCategoryCd
-- to populate table: codes_source_category
-- Generated on 2026-02-17
DROP TABLE IF EXISTS codes_source_category;

CREATE TABLE codes_source_category (
	source_code text PRIMARY KEY,
	source_code_name  text
);

INSERT INTO codes_source_category( source_code, source_code_name )
VALUES
	( 'ELECTRONIC',   'Electronic' ),
	( 'KEYED',   'Keyed manually' )
;

-- SQL statements generated by parsing the csv file: cover.csv
-- using field: electionTypeCd
-- to populate table: codes_election_type
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_election_type;
CREATE TABLE codes_election_type (
        electionTypeCd  text PRIMARY KEY,
        electionTypeCd_name  text
);

INSERT INTO codes_election_type( electionTypeCd, electionTypeCd_name )
VALUES
( 'OTHER',  'Other' ),
( 'UNKNOWN',  'Unknown' ),
( 'RUNOFF',  'Runoff' ),
( 'PRIMARY',  'Primary' ),
( 'SPECIAL',  'Special' ),
( 'GENERAL',  'General' );

-- SQL statements generated by parsing the csv file: cover.csv
-- using field: politicalPartyCd
-- to populate table: codes_political_party
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_political_party;
CREATE TABLE codes_political_party (
        politicalPartyCd  text PRIMARY KEY,
        politicalPartyCd_name  text
);

INSERT INTO codes_political_party( politicalPartyCd, politicalPartyCd_name )
VALUES
( 'DEM',  'Democratic' ),
( 'REP',  'Republican' ),
( 'OTHER',  'Other' ),
( 'LIB',  'Libertarian' );


-- SQL statements generated by parsing the csv file: cover.csv
-- using field: politicalDivisionCd
-- to populate table: codes_political_division
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_political_division;
CREATE TABLE codes_political_division (
        politicalDivisionCd  text PRIMARY KEY,
        politicalDivisionCd_name  text
);

INSERT INTO codes_political_division( politicalDivisionCd, politicalDivisionCd_name )
VALUES
( 'STATE',  'State' ),
( 'COUNTY',  'County' );


-- SQL statements generated by parsing the csv file: cover.csv
-- using field: highContribThreshholdCd
-- to populate table: codes_contrib_threshhold
-- Generated on 2026-02-17
-- NOTE: fieldname is misspelled in the csv file as "highContribThreshholdCd" instead of "highContribThresholdCd". The generated code uses the misspelled field name to match the csv file.
-- 
DROP TABLE IF EXISTS codes_contrib_threshold;
CREATE TABLE codes_contrib_threshold (
        highContribThreshholdCd  text PRIMARY KEY,
        highContribThreshholdCd_name  text
);

INSERT INTO codes_contrib_threshold( highContribThreshholdCd, highContribThreshholdCd_name )
VALUES
( 'Y',  'Y' ),
( 'N',  'N' ),
( 'YES',  'Yes' ),
( 'NO',  'No' );

